### ISSUE TITLE
Spending pane sometimes doesn't get populated

### ISSUE THREAD

**Issue by andrew-schofield** [robjtede/monux#102]
I've noticed a few times recently that while the transaction list works fine, the spending pane appears to remain empty.

![image](https://user-images.githubusercontent.com/8590162/28290251-9f04593a-6b3d-11e7-8a1a-f1b83964f008.png)

It's broken in packaged and unpackaged form :(

**Comment by andrew-schofield** [comment]
Ignore me, somehow d3 hadn't been included properly.

**Comment by robjtede** [comment]
I know that on first load it doesn’t render because it only takes from the cache.

**Comment by andrew-schofield** [comment]
Is that in itself a feature or a bug?

In the case I was reporting the developer console showed that bits of d3 were missing.

**Comment by robjtede** [comment]
It's a bug... lazy first implementation due to imminent change to use redux as the data store
