### ISSUE TITLE
monux.robjte.de down

### ISSUE THREAD

**Issue by dippergt750** [robjtede/monux#173]
Everything setup, but on login attempt error "cannot resolve name server"

**Comment by voarsh2** [comment]
@robjtede
Need to update URL for app

**Comment by dippergt750** [comment]
No, thank you.  

  

  

  

  
  
  
  
  
>

**Comment by voarsh2** [comment]
I'm saying the maintainer needs to fix

**Comment by dippergt750** [comment]
I have no idea what you are talking about.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by robjtede** [comment]
I let that domain go and kinda dropped the ball on maintaining the server for it but its back up now. You can swap out the `monux.robjte.de` for `monux.robjtede.dev` after clicking the email link.

FWIW, you can host your own [auth proxy](https://github.com/robjtede/monux-auth-proxy) but I intent to host that one for the forseeable future now.

I'm working on a getting a release out with the correct URLs baked-in and to finally use the code that's been sitting in master for 1+ years.
