### ISSUE TITLE
Authentication email link empty

### ISSUE THREAD

**Issue by jutkko** [robjtede/monux#72]
Hi Rob,

Nice project, the UI looks sleek and you got great ideas. Please keep it up!

I am failing to authenticate the app, since the email I get from Monzo does not have a valid link (I cannot even click on it). I have followed the instructions and put the `monux://auth/` to my client's Redirect URL field.

Any ideas why?

**Comment by robjtede** [comment]
Clicking on the link in the email should take you straight into the app. As in the app should register the monux:// scheme with macOS when you first open it. 

A potential workaround if you're sure the client details are correct is to copy the link from the email into a text editor and extract the "code" field. Add the following fields to your `config.json` located in ~/Library/Application Support/Monux

```
{
  "client_id": "oauthclient_xxx",
  "client_secret": "xxx",
  "authCode": "xxx",
  "accessToken": "[the code field extracted from email]",
  "authExpires": 21599000,
  "authTime": [current timestamp in seconds]
}
```

Authentication flow improvements are in the works.

**Comment by jutkko** [comment]
I can confirm that there is no link in the email whatsoever.

I also just had a look at the `config.json` in the directory and it looks correct, in fact the Monux shows the correct client name at the start.

**Comment by robjtede** [comment]
Hmmm if there is no link in the email at all then it's not a problem with he app's auth. You should be able to get the link by right clicking the "login to monzo" button and copying target link. 

Try recreating the client and deleting the `config.json` file.

**Comment by robjtede** [comment]
Hey @jutkko, some auth flow changed have been implemented in the latest release which may fix issues you had. You'll need to recreate your Monzo client as a confidential client.
